version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "8000:8000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"