apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fastapi-chart
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  chart:
    spec:
      chart: flux/helm/fastapi-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 2

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/templates/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
