apiVersion: v1
kind: Service
metadata:
  namespace: fast
  name: fastapi-app-service
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
  - name: http
    protocol: TCP
    port: 8000
    nodePort: 30000
